name: Vladimir Kostyukov
description: "Research & Engineering"
meta_description: ""

markdown: redcarpet
pygments: true
paginate: 15
permalink: /posts/:title

# Details for the RSS feed generator
url:            'http://vkostyukov.ru'
author:         'Vladimir Kostyukov'
