name: Vladimir Kostyukov
description: "Research & Engineering"
meta_description: ""

highlighter: true
paginate: 5
permalink: /posts/:title/

gems: 
  - jekyll-paginate
  - jekyll-feed

feed:
  path: rss.xml

url: 'http://vkostyukov.net'
author: 'Vladimir Kostyukov'
